<feat> 사용자 프로필 구현
dong-baeb/dong-baeb-back pull request #13
Opened 2024-08-10 17:48 UTC by mmanjuju

### 작업 상세 내용
- entity pakage에 setter를 내부 클래스로 대체
- @NotNull @NotEmpty -> @NotBlank 로 설정 후 에러 메세지 설정
- RestExceptionHandler 클래스 추가
- 예외 메세지 수정
- 

### 주의 사항

2024-08-11 12:51 UTC, nak-honest requested changes
많은 부분 잘 반영해 주셨네요!!
고생 많으셨습니다!!

남은 리뷰들만 다 완료(반영 or 논의) 가 되면 approve 드릴게요 :)

2024-08-11 12:51 UTC, nak-honest commented on gradlew.bat
> +echo location of your Java installation.
혹시 의도를 가지고 수정하신 걸까요??
표준 에러를 일반 출력과 동일하게 설정하신 것 같아서요!!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/controller/MemberController.java
> +    }
`@RequiredArgsConstructor` 로 대체할 수 있을 것 같네요!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/dto/MemberRequest.java
> +        @Size(min = 1, message = "최소 하나의 대학 ID가 필요합니다.")
사무 간사님은 학교 소속이 없으셔서 0개로 들어올 수도 있을거에요..!
학생이냐 간사냐에 따라 검증 로직이 달라질 것 같은데, 이후에 도메인에게 맡기는 방식으로 구현해보시죠 ㅎㅎ

일단 해당 부분은 삭제해 주시면 감사하겠습니닷!!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/entity/BaseEntity.java
> +    }
위에서 `@PresUpdate` 가 알아서 업데이트를 해주기 때문에 해당 메소드는 없어도 괜찮지 않을까 생각되네요!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/entity/Member.java
> +    private List<University> universities;
https://ict-nroo.tistory.com/127
이전에 위의 링크를 드렸던 건 `@ManyToMany`를 사용하지 않고, 
중간 테이블을 하나의 엔티티로 빼서 `@ManyToOne` 과 `@OneToMany`로 관리하는 게 좋을 것 같다는 의도였습니다!!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/entity/Member.java
> +public class Member extends BaseEntity {
`@ManyToMany`는 Lazy 로딩이 되기 때문에, 프록시 객체가 `Member`를 상속받게 됩니다.
이때 기본 생성자가 있어야 제대로 동작하기 때문에, 롬복으로 기본생성자를 추가해 주면 좋을 것 같아요!

자세한 내용은 Lazy 로딩, 프록시, 기본 생성자, 리플렉션 등의 키워드로 검색해보시면 좋을 것 같네요!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +    }
여기도 `@RequiredArgsConstructor` 로 대체할 수 있을 것 같네요!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +        member.setStudentNo(memberRequest.studentNo());
제가 setter를 지양하자고 했던 것은 단순히 롬복의 `@Setter`를 의미하는 것이 아니라 `setXxx` 메소드를 의미하는 것이었어요..!
그리고 현재 부분은 Member 객체를 생성해내는 작업이기 때문에 생성자나 정적 팩토리 메소드, 빌더 등에게 맡기는 것이 더 좋지 않을 까 생각되네요!

생성자가 왜 존재하는가 에 대해 고민해 보셔도 좋을 것 같습니다!!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +        member.setStudentNo(memberRequest.studentNo());
https://github.com/dong-baeb/dong-baeb-back/pull/11#discussion_r1712546418

그리고 위에서 드린 리뷰의 의도는, DTO의 변환 책임을 서비스가 아닌 DTO에 놓는 것은 어떤지 여쭈어 보려는 것이었습니다!!

이 [링크](https://lsh2016.tistory.com/147)의 내용이 저의 생각과 비슷해서 첨부해 봅니닷!!

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("해당 아이디를 가진 사용자를 찾을 수 없습니다: " + id));
DELETE 시 해당 값이 존재하지 않는다면, 에러 상황일까요 정상 상황일까요??
이 부분은 회사마다도 다 다르기 때문에 저희 팀에서 같이 결정해 보면 좋을 것 같아요!

일단은 에러 응답으로 두고, 담에 같이 이야기 해 보시죠 ㅎㅎ

2024-08-11 12:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/dto/MemberRequest.java
> +        // 이후 다른 소셜로그인 아이디가 추가될 수도 있어 kakaoId 대신 socialId와 socialProvider 같은 걸로 바꾸어야할 것 같습니다..
네네 맞습니다!

하지만 일단 카카오 로그인만 구현하기로 했으니, 그대로 두고 이후에 추가 되었을 때 분리해도 괜찮을 것 같아요!!
새로운 소셜 로그인이 도입된다면 아예 엔티티를 따로 빼거나 해야할 거에요!

2024-08-12 08:16 UTC, mmanjuju commented on gradlew.bat
> +echo location of your Java installation.
초기 intellij 다운받고 설정할때 뭔가 잘못 설정한것 같습니다.. 일부러 수정한 건 아닙니다ㅠㅠ

2024-08-12 08:18 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/controller/MemberController.java
> +    }
감사합니다. 수정했습니다!

2024-08-12 08:21 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/dto/MemberRequest.java
> +        @Size(min = 1, message = "최소 하나의 대학 ID가 필요합니다.")
좋습니다. 일단 해당 부분 삭제했습니다!

2024-08-12 08:25 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +    }
감사합니다. 수정했습니다!

2024-08-12 08:34 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("해당 아이디를 가진 사용자를 찾을 수 없습니다: " + id));
넵! 한 번 더 점검하는 식으로 싶어서 넣어뒀는데 다음에 같이 이야기 해봐요!
그런데 탈퇴(?) 하는 사용자를 아예 삭제 해야 할지 아니면 비활성화만 하고 일정기간이 지나면 삭제해야 할지 갑자기 고민되네요.. 탈퇴하고 다시 가입하는 사용자는 해당 정보를 남겨두지 않아도 괜찮은가요?

2024-08-12 08:37 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +        member.setStudentNo(memberRequest.studentNo());
DTO는 변수만 두고 이후에 다른 기능들에 이 변수가 필요하면 각 Service에서 변형할 수 있게 하려고 생각했는데 
변환 책임은 DTO에서 하는거 좋네요! 그렇게 수정해두겠습니다!
그리고 모르는 부분이 많아 해본 방식으로만 하는 것 같네요... 피드백 감사합니다!!

2024-08-12 08:54 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +        member.setStudentNo(memberRequest.studentNo());
com.dongbaeb.demo.profile.entity.Member와 com.dongbaeb.demo.profile.dto.MemberRequest에서 @Builder로 수정해두었습니닷!

2024-08-12 09:31 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/entity/Member.java
> +public class Member extends BaseEntity {
Builder 사용에도 필요해서

@NoArgsConstructor
@AllArgsConstructor

추가했습니다!

2024-08-12 10:21 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/entity/Member.java
> +    private List<University> universities;
일단 코드 작성해봤는데 불필요하거나 문제있는 부분 봐주시면 감사하겠습니다!

2024-08-13 03:51 UTC, nak-honest commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("해당 아이디를 가진 사용자를 찾을 수 없습니다: " + id));
넵 말씀하신대로 멤버는 soft delete로 구현하는 것이 좋죠!!

그런데 저희 기능 명세에서는 아직 멤버 탈퇴가 없고, MVP에서도 없는 기능이라 API를 구현해 놓아야 할지는 잘 모르겠네요..!

soft delete를`@SqlDelete` 이랑 `@SQLRestriction`으로 구현하는게 가장 간편한 방법이기는 한데, 이게 JPQL 등에는 적용이 안되어서 복잡해지는 경향이 있습니다.
그렇다고 직접 구현하는 것은 앞으로 모든 조회/수정 에서 WHERE 절을 달아주어야 하구요..!

여러 고려사항들이 많아서 그중 하나를 선택해야 하는데, 지금 결정하기에는 이르지 않나 싶습니다 :)

2024-08-14 01:21 UTC, LSe-Yeong approved these changes
코드 확인 완료했습니다! 개인적인 의견은 코드 중간에(?) 올려놨습니다! 이후 merge되면 바로 이어서 작업 진행하겠습니다!

2024-08-14 05:27 UTC, nak-honest approved these changes
확인 완료하였습니다!
몇가지 더 리뷰를 드리고 싶긴하지만,,, ^_^
지금까지 너무 많이 드린 것 같아서 ㅎㅎ 일단 approve 드리겠습니다!

merge 되면 테스트 코드랑 리팩토링 작업 따로 해볼게요!!
고생 많으셨습니다!!

2024-08-15 00:43 UTC, mmanjuju commented on src/main/java/com/dongbaeb/demo/profile/service/MemberService.java
넵 이후에 추가해보도록 하겠습니다. 감사합니다!

2024-08-15 00:45 UTC, merged